import numpy as np

import torch
from torch import nn
from torchvision.transforms import transforms
from efficientnet_pytorch import EfficientNet
from PIL import Image
import streamlit as st

target = ['Voltorb',
 'NidoranM',
 'Nidorino',
 'Jynx',
 'Persian',
 'Dewgong',
 'Snorlax',
 'Weepinbell',
 'Jigglypuff',
 'Clefairy',
 'Charmander',
 'Abra',
 'Poliwhirl',
 'Seel',
 'Rapidash',
 'Victreebel',
 'Omanyte',
 'Kakuna',
 'CharizardMega Charizard X',
 'Gengar',
 'Horsea',
 'Pidgeot',
 'Hitmonchan',
 'Slowbro',
 'Golbat',
 'Ivysaur',
 'Electabuzz',
 'Beedrill',
 'Scyther',
 'Rhydon',
 'Kabutops',
 'Doduo',
 'Hitmonlee',
 'Cloyster',
 'Kadabra',
 'Weedle',
 'Sandshrew',
 'Oddish',
 'Mewtwo',
 'Staryu',
 'Alakazam',
 'Spearow',
 'Kangaskhan',
 'Fearow',
 'Tentacool',
 'AlakazamMega Alakazam',
 'Blastoise',
 'Nidoking',
 'MewtwoMega Mewtwo Y',
 'Drowzee',
 'Nidorina',
 'Mr',
 'Raichu',
 'Dratini',
 'Weezing',
 'MewtwoMega Mewtwo X',
 'Raticate',
 'Shellder',
 'Lickitung',
 'Ponyta',
 'Kingler',
 'Pidgey',
 'Machop',
 'Ninetales',
 'Poliwag',
 'Metapod',
 'Marowak',
 'Vaporeon',
 'Pinsir',
 'Venusaur',
 'Wigglytuff',
 'Venomoth',
 'Gloom',
 'Dragonair',
 'Magnemite',
 'Bulbasaur',
 'Tauros',
 'Flareon',
 'Meowth',
 'Muk',
 'Machamp',
 'GengarMega Gengar',
 'Eevee',
 'Vulpix',
 'Butterfree',
 'Poliwrath',
 'Charizard',
 'Vileplume',
 'Chansey',
 'Kabuto',
 'Rattata',
 'Golem',
 'Mew',
 'Grimer',
 'Cubone',
 'Mankey',
 'Starmie',
 'AerodactylMega Aerodactyl',
 'Nidoqueen',
 'Porygon',
 'Seadra',
 'Machoke',
 'Arbok',
 'Exeggcute',
 'KangaskhanMega Kangaskhan',
 'Moltres',
 'Pikachu',
 'Tangela',
 'Lapras',
 'Squirtle',
 'Geodude',
 'Graveler',
 'Articuno',
 'Exeggutor',
 'Krabby',
 'Clefable',
 'PinsirMega Pinsir',
 'Ekans',
 'Primeape',
 'Dragonite',
 'BlastoiseMega Blastoise',
 'Aerodactyl',
 'Bellsprout',
 'Electrode',
 'Dodrio',
 'VenusaurMega Venusaur',
 'Gyarados',
 'Haunter',
 'Farfetchd',
 'CharizardMega Charizard Y',
 'Gastly',
 'Goldeen',
 'SlowbroMega Slowbro',
 'Zapdos',
 'Koffing',
 'Arcanine',
 'Sandslash',
 'GyaradosMega Gyarados',
 'Golduck',
 'Growlithe',
 'Magneton',
 'Onix',
 'Slowpoke',
 'Charmeleon',
 'Nidoran',
 'Rhyhorn',
 'Psyduck',
 'Magikarp',
 'Ditto',
 'Venonat',
 'Omastar',
 'Dugtrio',
 'Paras',
 'Zubat',
 'Hypno',
 'BeedrillMega Beedrill',
 'PidgeotMega Pidgeot',
 'Pidgeotto',
 'Seaking',
 'Caterpie',
 'Jolteon',
 'Diglett',
 'Wartortle',
 'Tentacruel',
 'Magmar',
 'Parasect']

transform = transforms.Compose([
    transforms.Resize((100, 100)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5),
                          (0.5, 0.5, 0.5))
])

model = EfficientNet.from_name("efficientnet-b0")
model._fc = nn.Linear(1280, len(target))

model.load_state_dict(torch.load('model.pt', map_location=torch.device('cpu')))
model.eval()

img = st.file_uploader("Upload Image", type=['jpeg', 'jpg', 'png'])
img = Image.open(img).convert('RGB')

img = transform(img)

out = model(img.unsqueeze(0))

st.write(torch.max(out, 1)[1])

